name: 'GitHub action demo'
on:
  schedule:
    - cron:  '30 3 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: hello world
        id: step_one
        env:
          key: ${{ secrets.KEY }}
          message: "HELLO WORLD"
        run: |
          python main.py
          echo 'job complete!'

