name: 'Send good night words'
on:
  schedule:
    - cron:  '30 14 * * *'  # 22:30 am UTC+8
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send good night words
        id: step_one
        env:
          send_key: ${{ secrets.SEND_KEY }}
          send_url: ${{ secrets.SEND_URL }}
          tian_api_key: ${{ secrets.TIAN_API_KEY }}
        run: |
          python good_night.py
          echo 'job complete!'
